server:
  port: 8080

  r2dbc:
    url: ""
    username: "root"
    password: "password"
  main:
    allow-bean-definition-overriding: true

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
