server:
  port: 8080

spring:
  flyway:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8
    user: root
    password: password
    locations: classpath:db/migration
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8
    user: root
    password: password

  main:
    allow-bean-definition-overriding: true

springdoc:
  version: '@springdoc.version@'
  webjars:
    prefix: /
  swagger-ui:
    use-root-path: true

