server:
  port: 8080

spring:
  r2dbc:
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
    url: r2dbc:postgresql://postgres:5432/test
    username: test
    password: password

  main:
    allow-bean-definition-overriding: true

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    enabled: true

