server:
  port: 8080

spring:
  r2dbc:
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
    url: r2dbc:mysql://mysql:3306/test?characterEncoding=utf-8
    password: password
    username: root

  main:
    allow-bean-definition-overriding: true

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
